// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: payload.proto

package com.xabe.binary.protocol.payload;

public final class PayloadProtubuf {
  private PayloadProtubuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PayloadOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Payload)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 number = 1;</code>
     */
    int getNumber();

    /**
     * <code>string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>bool active = 3;</code>
     */
    boolean getActive();

    /**
     * <code>.Timestamp date = 4;</code>
     */
    boolean hasDate();
    /**
     * <code>.Timestamp date = 4;</code>
     */
    com.xabe.binary.protocol.payload.PayloadProtubuf.Timestamp getDate();
    /**
     * <code>.Timestamp date = 4;</code>
     */
    com.xabe.binary.protocol.payload.PayloadProtubuf.TimestampOrBuilder getDateOrBuilder();
  }
  /**
   * Protobuf type {@code Payload}
   */
  public  static final class Payload extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Payload)
      PayloadOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Payload.newBuilder() to construct.
    private Payload(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Payload() {
      number_ = 0;
      name_ = "";
      active_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Payload(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              number_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 24: {

              active_ = input.readBool();
              break;
            }
            case 34: {
              com.xabe.binary.protocol.payload.PayloadProtubuf.Timestamp.Builder subBuilder = null;
              if (date_ != null) {
                subBuilder = date_.toBuilder();
              }
              date_ = input.readMessage(com.xabe.binary.protocol.payload.PayloadProtubuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(date_);
                date_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xabe.binary.protocol.payload.PayloadProtubuf.internal_static_Payload_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xabe.binary.protocol.payload.PayloadProtubuf.internal_static_Payload_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xabe.binary.protocol.payload.PayloadProtubuf.Payload.class, com.xabe.binary.protocol.payload.PayloadProtubuf.Payload.Builder.class);
    }

    public static final int NUMBER_FIELD_NUMBER = 1;
    private int number_;
    /**
     * <code>int32 number = 1;</code>
     */
    public int getNumber() {
      return number_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACTIVE_FIELD_NUMBER = 3;
    private boolean active_;
    /**
     * <code>bool active = 3;</code>
     */
    public boolean getActive() {
      return active_;
    }

    public static final int DATE_FIELD_NUMBER = 4;
    private com.xabe.binary.protocol.payload.PayloadProtubuf.Timestamp date_;
    /**
     * <code>.Timestamp date = 4;</code>
     */
    public boolean hasDate() {
      return date_ != null;
    }
    /**
     * <code>.Timestamp date = 4;</code>
     */
    public com.xabe.binary.protocol.payload.PayloadProtubuf.Timestamp getDate() {
      return date_ == null ? com.xabe.binary.protocol.payload.PayloadProtubuf.Timestamp.getDefaultInstance() : date_;
    }
    /**
     * <code>.Timestamp date = 4;</code>
     */
    public com.xabe.binary.protocol.payload.PayloadProtubuf.TimestampOrBuilder getDateOrBuilder() {
      return getDate();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (number_ != 0) {
        output.writeInt32(1, number_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (active_ != false) {
        output.writeBool(3, active_);
      }
      if (date_ != null) {
        output.writeMessage(4, getDate());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (number_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, number_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (active_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, active_);
      }
      if (date_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getDate());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.xabe.binary.protocol.payload.PayloadProtubuf.Payload)) {
        return super.equals(obj);
      }
      com.xabe.binary.protocol.payload.PayloadProtubuf.Payload other = (com.xabe.binary.protocol.payload.PayloadProtubuf.Payload) obj;

      boolean result = true;
      result = result && (getNumber()
          == other.getNumber());
      result = result && getName()
          .equals(other.getName());
      result = result && (getActive()
          == other.getActive());
      result = result && (hasDate() == other.hasDate());
      if (hasDate()) {
        result = result && getDate()
            .equals(other.getDate());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getNumber();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + ACTIVE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getActive());
      if (hasDate()) {
        hash = (37 * hash) + DATE_FIELD_NUMBER;
        hash = (53 * hash) + getDate().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.xabe.binary.protocol.payload.PayloadProtubuf.Payload parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xabe.binary.protocol.payload.PayloadProtubuf.Payload parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xabe.binary.protocol.payload.PayloadProtubuf.Payload parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xabe.binary.protocol.payload.PayloadProtubuf.Payload parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xabe.binary.protocol.payload.PayloadProtubuf.Payload parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xabe.binary.protocol.payload.PayloadProtubuf.Payload parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xabe.binary.protocol.payload.PayloadProtubuf.Payload parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xabe.binary.protocol.payload.PayloadProtubuf.Payload parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xabe.binary.protocol.payload.PayloadProtubuf.Payload parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.xabe.binary.protocol.payload.PayloadProtubuf.Payload parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xabe.binary.protocol.payload.PayloadProtubuf.Payload parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xabe.binary.protocol.payload.PayloadProtubuf.Payload parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.xabe.binary.protocol.payload.PayloadProtubuf.Payload prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Payload}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Payload)
        com.xabe.binary.protocol.payload.PayloadProtubuf.PayloadOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xabe.binary.protocol.payload.PayloadProtubuf.internal_static_Payload_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xabe.binary.protocol.payload.PayloadProtubuf.internal_static_Payload_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xabe.binary.protocol.payload.PayloadProtubuf.Payload.class, com.xabe.binary.protocol.payload.PayloadProtubuf.Payload.Builder.class);
      }

      // Construct using com.xabe.binary.protocol.payload.PayloadProtubuf.Payload.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        number_ = 0;

        name_ = "";

        active_ = false;

        if (dateBuilder_ == null) {
          date_ = null;
        } else {
          date_ = null;
          dateBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xabe.binary.protocol.payload.PayloadProtubuf.internal_static_Payload_descriptor;
      }

      @java.lang.Override
      public com.xabe.binary.protocol.payload.PayloadProtubuf.Payload getDefaultInstanceForType() {
        return com.xabe.binary.protocol.payload.PayloadProtubuf.Payload.getDefaultInstance();
      }

      @java.lang.Override
      public com.xabe.binary.protocol.payload.PayloadProtubuf.Payload build() {
        com.xabe.binary.protocol.payload.PayloadProtubuf.Payload result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.xabe.binary.protocol.payload.PayloadProtubuf.Payload buildPartial() {
        com.xabe.binary.protocol.payload.PayloadProtubuf.Payload result = new com.xabe.binary.protocol.payload.PayloadProtubuf.Payload(this);
        result.number_ = number_;
        result.name_ = name_;
        result.active_ = active_;
        if (dateBuilder_ == null) {
          result.date_ = date_;
        } else {
          result.date_ = dateBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xabe.binary.protocol.payload.PayloadProtubuf.Payload) {
          return mergeFrom((com.xabe.binary.protocol.payload.PayloadProtubuf.Payload)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xabe.binary.protocol.payload.PayloadProtubuf.Payload other) {
        if (other == com.xabe.binary.protocol.payload.PayloadProtubuf.Payload.getDefaultInstance()) return this;
        if (other.getNumber() != 0) {
          setNumber(other.getNumber());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getActive() != false) {
          setActive(other.getActive());
        }
        if (other.hasDate()) {
          mergeDate(other.getDate());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.xabe.binary.protocol.payload.PayloadProtubuf.Payload parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.xabe.binary.protocol.payload.PayloadProtubuf.Payload) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int number_ ;
      /**
       * <code>int32 number = 1;</code>
       */
      public int getNumber() {
        return number_;
      }
      /**
       * <code>int32 number = 1;</code>
       */
      public Builder setNumber(int value) {
        
        number_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 number = 1;</code>
       */
      public Builder clearNumber() {
        
        number_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private boolean active_ ;
      /**
       * <code>bool active = 3;</code>
       */
      public boolean getActive() {
        return active_;
      }
      /**
       * <code>bool active = 3;</code>
       */
      public Builder setActive(boolean value) {
        
        active_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool active = 3;</code>
       */
      public Builder clearActive() {
        
        active_ = false;
        onChanged();
        return this;
      }

      private com.xabe.binary.protocol.payload.PayloadProtubuf.Timestamp date_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.xabe.binary.protocol.payload.PayloadProtubuf.Timestamp, com.xabe.binary.protocol.payload.PayloadProtubuf.Timestamp.Builder, com.xabe.binary.protocol.payload.PayloadProtubuf.TimestampOrBuilder> dateBuilder_;
      /**
       * <code>.Timestamp date = 4;</code>
       */
      public boolean hasDate() {
        return dateBuilder_ != null || date_ != null;
      }
      /**
       * <code>.Timestamp date = 4;</code>
       */
      public com.xabe.binary.protocol.payload.PayloadProtubuf.Timestamp getDate() {
        if (dateBuilder_ == null) {
          return date_ == null ? com.xabe.binary.protocol.payload.PayloadProtubuf.Timestamp.getDefaultInstance() : date_;
        } else {
          return dateBuilder_.getMessage();
        }
      }
      /**
       * <code>.Timestamp date = 4;</code>
       */
      public Builder setDate(com.xabe.binary.protocol.payload.PayloadProtubuf.Timestamp value) {
        if (dateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          date_ = value;
          onChanged();
        } else {
          dateBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Timestamp date = 4;</code>
       */
      public Builder setDate(
          com.xabe.binary.protocol.payload.PayloadProtubuf.Timestamp.Builder builderForValue) {
        if (dateBuilder_ == null) {
          date_ = builderForValue.build();
          onChanged();
        } else {
          dateBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Timestamp date = 4;</code>
       */
      public Builder mergeDate(com.xabe.binary.protocol.payload.PayloadProtubuf.Timestamp value) {
        if (dateBuilder_ == null) {
          if (date_ != null) {
            date_ =
              com.xabe.binary.protocol.payload.PayloadProtubuf.Timestamp.newBuilder(date_).mergeFrom(value).buildPartial();
          } else {
            date_ = value;
          }
          onChanged();
        } else {
          dateBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Timestamp date = 4;</code>
       */
      public Builder clearDate() {
        if (dateBuilder_ == null) {
          date_ = null;
          onChanged();
        } else {
          date_ = null;
          dateBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Timestamp date = 4;</code>
       */
      public com.xabe.binary.protocol.payload.PayloadProtubuf.Timestamp.Builder getDateBuilder() {
        
        onChanged();
        return getDateFieldBuilder().getBuilder();
      }
      /**
       * <code>.Timestamp date = 4;</code>
       */
      public com.xabe.binary.protocol.payload.PayloadProtubuf.TimestampOrBuilder getDateOrBuilder() {
        if (dateBuilder_ != null) {
          return dateBuilder_.getMessageOrBuilder();
        } else {
          return date_ == null ?
              com.xabe.binary.protocol.payload.PayloadProtubuf.Timestamp.getDefaultInstance() : date_;
        }
      }
      /**
       * <code>.Timestamp date = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.xabe.binary.protocol.payload.PayloadProtubuf.Timestamp, com.xabe.binary.protocol.payload.PayloadProtubuf.Timestamp.Builder, com.xabe.binary.protocol.payload.PayloadProtubuf.TimestampOrBuilder> 
          getDateFieldBuilder() {
        if (dateBuilder_ == null) {
          dateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.xabe.binary.protocol.payload.PayloadProtubuf.Timestamp, com.xabe.binary.protocol.payload.PayloadProtubuf.Timestamp.Builder, com.xabe.binary.protocol.payload.PayloadProtubuf.TimestampOrBuilder>(
                  getDate(),
                  getParentForChildren(),
                  isClean());
          date_ = null;
        }
        return dateBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Payload)
    }

    // @@protoc_insertion_point(class_scope:Payload)
    private static final com.xabe.binary.protocol.payload.PayloadProtubuf.Payload DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.xabe.binary.protocol.payload.PayloadProtubuf.Payload();
    }

    public static com.xabe.binary.protocol.payload.PayloadProtubuf.Payload getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Payload>
        PARSER = new com.google.protobuf.AbstractParser<Payload>() {
      @java.lang.Override
      public Payload parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Payload(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Payload> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Payload> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.xabe.binary.protocol.payload.PayloadProtubuf.Payload getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TimestampOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Timestamp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Represents seconds of UTC time since Unix epoch
     * 1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to
     * 9999-12-31T23:59:59Z inclusive.
     * </pre>
     *
     * <code>int64 seconds = 1;</code>
     */
    long getSeconds();

    /**
     * <pre>
     * Non-negative fractions of a second at nanosecond resolution. Negative
     * second values with fractions must still have non-negative nanos values
     * that count forward in time. Must be from 0 to 999,999,999
     * inclusive.
     * </pre>
     *
     * <code>int32 nanos = 2;</code>
     */
    int getNanos();
  }
  /**
   * Protobuf type {@code Timestamp}
   */
  public  static final class Timestamp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Timestamp)
      TimestampOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Timestamp.newBuilder() to construct.
    private Timestamp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Timestamp() {
      seconds_ = 0L;
      nanos_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Timestamp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              seconds_ = input.readInt64();
              break;
            }
            case 16: {

              nanos_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xabe.binary.protocol.payload.PayloadProtubuf.internal_static_Timestamp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xabe.binary.protocol.payload.PayloadProtubuf.internal_static_Timestamp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xabe.binary.protocol.payload.PayloadProtubuf.Timestamp.class, com.xabe.binary.protocol.payload.PayloadProtubuf.Timestamp.Builder.class);
    }

    public static final int SECONDS_FIELD_NUMBER = 1;
    private long seconds_;
    /**
     * <pre>
     * Represents seconds of UTC time since Unix epoch
     * 1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to
     * 9999-12-31T23:59:59Z inclusive.
     * </pre>
     *
     * <code>int64 seconds = 1;</code>
     */
    public long getSeconds() {
      return seconds_;
    }

    public static final int NANOS_FIELD_NUMBER = 2;
    private int nanos_;
    /**
     * <pre>
     * Non-negative fractions of a second at nanosecond resolution. Negative
     * second values with fractions must still have non-negative nanos values
     * that count forward in time. Must be from 0 to 999,999,999
     * inclusive.
     * </pre>
     *
     * <code>int32 nanos = 2;</code>
     */
    public int getNanos() {
      return nanos_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (seconds_ != 0L) {
        output.writeInt64(1, seconds_);
      }
      if (nanos_ != 0) {
        output.writeInt32(2, nanos_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (seconds_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, seconds_);
      }
      if (nanos_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, nanos_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.xabe.binary.protocol.payload.PayloadProtubuf.Timestamp)) {
        return super.equals(obj);
      }
      com.xabe.binary.protocol.payload.PayloadProtubuf.Timestamp other = (com.xabe.binary.protocol.payload.PayloadProtubuf.Timestamp) obj;

      boolean result = true;
      result = result && (getSeconds()
          == other.getSeconds());
      result = result && (getNanos()
          == other.getNanos());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SECONDS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSeconds());
      hash = (37 * hash) + NANOS_FIELD_NUMBER;
      hash = (53 * hash) + getNanos();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.xabe.binary.protocol.payload.PayloadProtubuf.Timestamp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xabe.binary.protocol.payload.PayloadProtubuf.Timestamp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xabe.binary.protocol.payload.PayloadProtubuf.Timestamp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xabe.binary.protocol.payload.PayloadProtubuf.Timestamp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xabe.binary.protocol.payload.PayloadProtubuf.Timestamp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xabe.binary.protocol.payload.PayloadProtubuf.Timestamp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xabe.binary.protocol.payload.PayloadProtubuf.Timestamp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xabe.binary.protocol.payload.PayloadProtubuf.Timestamp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xabe.binary.protocol.payload.PayloadProtubuf.Timestamp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.xabe.binary.protocol.payload.PayloadProtubuf.Timestamp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xabe.binary.protocol.payload.PayloadProtubuf.Timestamp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xabe.binary.protocol.payload.PayloadProtubuf.Timestamp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.xabe.binary.protocol.payload.PayloadProtubuf.Timestamp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Timestamp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Timestamp)
        com.xabe.binary.protocol.payload.PayloadProtubuf.TimestampOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xabe.binary.protocol.payload.PayloadProtubuf.internal_static_Timestamp_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xabe.binary.protocol.payload.PayloadProtubuf.internal_static_Timestamp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xabe.binary.protocol.payload.PayloadProtubuf.Timestamp.class, com.xabe.binary.protocol.payload.PayloadProtubuf.Timestamp.Builder.class);
      }

      // Construct using com.xabe.binary.protocol.payload.PayloadProtubuf.Timestamp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        seconds_ = 0L;

        nanos_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xabe.binary.protocol.payload.PayloadProtubuf.internal_static_Timestamp_descriptor;
      }

      @java.lang.Override
      public com.xabe.binary.protocol.payload.PayloadProtubuf.Timestamp getDefaultInstanceForType() {
        return com.xabe.binary.protocol.payload.PayloadProtubuf.Timestamp.getDefaultInstance();
      }

      @java.lang.Override
      public com.xabe.binary.protocol.payload.PayloadProtubuf.Timestamp build() {
        com.xabe.binary.protocol.payload.PayloadProtubuf.Timestamp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.xabe.binary.protocol.payload.PayloadProtubuf.Timestamp buildPartial() {
        com.xabe.binary.protocol.payload.PayloadProtubuf.Timestamp result = new com.xabe.binary.protocol.payload.PayloadProtubuf.Timestamp(this);
        result.seconds_ = seconds_;
        result.nanos_ = nanos_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xabe.binary.protocol.payload.PayloadProtubuf.Timestamp) {
          return mergeFrom((com.xabe.binary.protocol.payload.PayloadProtubuf.Timestamp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xabe.binary.protocol.payload.PayloadProtubuf.Timestamp other) {
        if (other == com.xabe.binary.protocol.payload.PayloadProtubuf.Timestamp.getDefaultInstance()) return this;
        if (other.getSeconds() != 0L) {
          setSeconds(other.getSeconds());
        }
        if (other.getNanos() != 0) {
          setNanos(other.getNanos());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.xabe.binary.protocol.payload.PayloadProtubuf.Timestamp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.xabe.binary.protocol.payload.PayloadProtubuf.Timestamp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long seconds_ ;
      /**
       * <pre>
       * Represents seconds of UTC time since Unix epoch
       * 1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to
       * 9999-12-31T23:59:59Z inclusive.
       * </pre>
       *
       * <code>int64 seconds = 1;</code>
       */
      public long getSeconds() {
        return seconds_;
      }
      /**
       * <pre>
       * Represents seconds of UTC time since Unix epoch
       * 1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to
       * 9999-12-31T23:59:59Z inclusive.
       * </pre>
       *
       * <code>int64 seconds = 1;</code>
       */
      public Builder setSeconds(long value) {
        
        seconds_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Represents seconds of UTC time since Unix epoch
       * 1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to
       * 9999-12-31T23:59:59Z inclusive.
       * </pre>
       *
       * <code>int64 seconds = 1;</code>
       */
      public Builder clearSeconds() {
        
        seconds_ = 0L;
        onChanged();
        return this;
      }

      private int nanos_ ;
      /**
       * <pre>
       * Non-negative fractions of a second at nanosecond resolution. Negative
       * second values with fractions must still have non-negative nanos values
       * that count forward in time. Must be from 0 to 999,999,999
       * inclusive.
       * </pre>
       *
       * <code>int32 nanos = 2;</code>
       */
      public int getNanos() {
        return nanos_;
      }
      /**
       * <pre>
       * Non-negative fractions of a second at nanosecond resolution. Negative
       * second values with fractions must still have non-negative nanos values
       * that count forward in time. Must be from 0 to 999,999,999
       * inclusive.
       * </pre>
       *
       * <code>int32 nanos = 2;</code>
       */
      public Builder setNanos(int value) {
        
        nanos_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Non-negative fractions of a second at nanosecond resolution. Negative
       * second values with fractions must still have non-negative nanos values
       * that count forward in time. Must be from 0 to 999,999,999
       * inclusive.
       * </pre>
       *
       * <code>int32 nanos = 2;</code>
       */
      public Builder clearNanos() {
        
        nanos_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Timestamp)
    }

    // @@protoc_insertion_point(class_scope:Timestamp)
    private static final com.xabe.binary.protocol.payload.PayloadProtubuf.Timestamp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.xabe.binary.protocol.payload.PayloadProtubuf.Timestamp();
    }

    public static com.xabe.binary.protocol.payload.PayloadProtubuf.Timestamp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Timestamp>
        PARSER = new com.google.protobuf.AbstractParser<Timestamp>() {
      @java.lang.Override
      public Timestamp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Timestamp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Timestamp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Timestamp> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.xabe.binary.protocol.payload.PayloadProtubuf.Timestamp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Payload_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Payload_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Timestamp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Timestamp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rpayload.proto\"Q\n\007Payload\022\016\n\006number\030\001 \001" +
      "(\005\022\014\n\004name\030\002 \001(\t\022\016\n\006active\030\003 \001(\010\022\030\n\004date" +
      "\030\004 \001(\0132\n.Timestamp\"+\n\tTimestamp\022\017\n\007secon" +
      "ds\030\001 \001(\003\022\r\n\005nanos\030\002 \001(\005B3\n com.xabe.bina" +
      "ry.protocol.payloadB\017PayloadProtubufb\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Payload_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Payload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Payload_descriptor,
        new java.lang.String[] { "Number", "Name", "Active", "Date", });
    internal_static_Timestamp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Timestamp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Timestamp_descriptor,
        new java.lang.String[] { "Seconds", "Nanos", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
